### ISSUE TITLE
About  ID  

### ISSUE THREAD

**Issue by Jupitor1** [chipsalliance/Cores-SweRV-EL2#19]
Hi，
I am puzzled why the DMA_ID is  set to 1. Can I change it myself? How to change if possible

BR

**Comment by agrobman** [comment]
what is the DMA_ID ? Did you mean DMA_BUS_TAG ? If so,  use -set dma_bus_tag=N when run swerv.config script..

**Comment by Jupitor1** [comment]
thanks , It‘s useful
