### ISSUE TITLE
How to configure to reach 4.3 in the CoreMark test

### ISSUE THREAD

**Issue by tsuijian** [chipsalliance/Cores-SweRV-EL2#22]
At CoreMark Test ，
I achieved 3.62 ，lower than the official website‘s value of 4.3
How to configure to reach 4.3 in the CoreMark test

**Comment by aprnath** [comment]
See https://github.com/chipsalliance/Cores-SweRV/issues/104 as a hint to compiler switches.

**Comment by Yangg152** [comment]
> See [chipsalliance/Cores-VeeR-EH1#104](https://github.com/chipsalliance/Cores-VeeR-EH1/issues/104) as a hint to compiler switches.

Hello, I referred to the configuration parameters of the EH1, but the CoreMark results on the EL2 still show some discrepancies. Could you provide compiler options for me?
